fix: `ValueManager.getTimestampFromDate` method. (#459)
* fix: `ValueManager.getTimestampFromDate` method.

```
 4 actionable tasks: 4 executed
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler output below.
  Note: Recompile with -Xlint:deprecation for details.
  Note: Some input files use or override a deprecated API.
  /home/runner/work/adempiere-processors-service/adempiere-processors-service/src/main/java/org/spin/processor/service/Service.java:47: error: cannot find symbol
  				ValueManager.getTimestampFromDate(
  				            ^
    symbol:   method getTimestampFromDate(Timestamp)
    location: class ValueManager
  1 error
  ```

* change to deprecated.